### PR TITLE
Add Jennys Wallpapers Testnet App

### PR DESCRIPTION
**Pull request by cryptobabel**
Example of in-app Lightning Network payments on crypto enabled wallpapers.

### CODE REVIEW

**Comment by lightningnetworkstores** [comment]
Downloaded app, clicked in the thunder symbol but nothing happened. How does one pay the lightning?
screenshot_2018-04-09-03-59-43

**Comment by cryptobabel** [comment]
Good call. That was supposed to just be a signifier. You can click the other 'button'. That said based off your review i'm going to go update this. Thank you.

**Comment by lightningnetworkstores** [comment]
Great. now I see it. Are you thinking about coming soon to the mainnet? If yes, I can add you to the coming soon section of the mainnet, this way you get way more visibility. Not many people see the testnet page...

**Comment by cryptobabel** [comment]
I do have plans to bring it to mainnet soon-ish. Just need to work out some concerns around the in-app rules.

**Pull request merged**
