### PR TITLE
Added microbet site on mainnet and testnet

### PR DESCRIPTION
**Pull request by grunch**
Added microbet site on mainnet and testnet

### CODE REVIEW

**Comment by pedro-roberto** [comment]
Thanks for the PR, I am busy now... can you please submit the store with the form on the website?

**Comment by grunch** [comment]
yes sure, can I have a contributor code?

**Comment by pedro-roberto** [comment]
sure, I sent you by email

**Comment by pedro-roberto** [comment]
Added through form on website and manually. Think I forgot to activate the automatic upload for testnet stores... well will fix later, not urgent...

**Pull request closed without merging**
