### PR TITLE
Update sites.json

### PR DESCRIPTION
**Pull request by lndhub**
ask to add t8dream.team

### CODE REVIEW

**Comment by pedro-roberto** [comment]
Added, thanks

**Comment by verretor** [comment]
May I recommend that commit messages look more like this? :
Add [some site]

**Comment by pedro-roberto** [comment]
hi, ok will stick to that format. Good timing as I am launching automatic submission of stores through the website soon...

**Comment by pedro-roberto** [comment]
By the way, if you want to help testing join me on lnd slack, test server is http://eatpopcorns.com:8083/

**Pull request merged**
