### PR TITLE
added three card monte game to sites.json

### PR DESCRIPTION
**Pull request by pseudozach**
thanks for the service, I'm back with my mainnet game. I hope you merge.

### CODE REVIEW

**Comment by pedro-roberto** [comment]
Hi, have you tried the online tool to add the store? It's much easier for both of us if you add that way.

**Comment by pseudozach** [comment]
I figured since I know how to do this and having done this before I'll do it this way. Plus I'll keep developing more lapps.
but anyway, sure, I'll try the online tool.

**Comment by pseudozach** [comment]
done. But here's another problem:
I'm trying to add my other lapp at address: https://kriptode.com/receivesms/index.html
I receive an error: "Seems that store already exists: domain in use"
I'll be using this domain for all my projects. can you disable this check?

**Comment by pedro-roberto** [comment]
I can add an exception to your website but that check is there to prevent
spam. Is I remove it, other people may troll with your website, adding fake
copies...

Em sáb, 22 de dez de 2018 às 09:06, pseudozach <notifications@github.com>
escreveu:

**Comment by pseudozach** [comment]
please add the exception for my site thank you. you could check if the full url already exists instead of domain if you want to avoid duplicates.

**Comment by pedro-roberto** [comment]
Done. Changed the name to Kriptode too.

**Pull request closed without merging**
