### PR TITLE
Update sites.json

### PR DESCRIPTION
**Pull request by dumm98**

### CODE REVIEW

**Comment by dumm98** [comment]
ty

**Comment by pedro-roberto** [comment]
Thanks for the PR. The sites.json file has a curvy parenthesis from line 90 should go to the end of the document.

Hint: Use a json checker like this website: https://jsonformatter.curiousconcept.com/

**Comment by dumm98** [comment]
edited. thanks for the hint

**Comment by lightningnetworkstores** [comment]
Better still "Lightning Shop EU"

**Comment by lightningnetworkstores** [comment]
Thanks!

**Pull request merged**
